### ISSUE TITLE
功能建议

### ISSUE THREAD

**Issue by hivee** [gin-18/lottery#15]
兄弟，你这项目很好，能否增加最近n期的号码出现的柱状图功能，系统不可能一直摇热号。只能守温冷了

**Comment by gin-18** [comment]
感谢反馈，这个issue关闭在[310b3b41c2c59250faaa6e292d54bf0fb065e93e](https://github.com/gin-18/lottery/commit/310b3b41c2c59250faaa6e292d54bf0fb065e93e)
